nome = str(input('Digite seu nome completo:')).strip()
pn = nome.split()
un = nome.split()
print(' Muito prazer em te conhecer! ')
print('Seu primeiro nome {}'.format(pn[0]))
print('Seu último nome é {}'.format(un[-1]))
